version: '3.9'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data

